### ISSUE TITLE
Get mac by tcp

### ISSUE THREAD

**Issue by Vetalcraft** [btccom/libbtctools#1]
Hello!

Request *req = new Request;
			req->host_ = ip;
			req->port_ = "4028";
			req->content_ = "stats|";  //Does not return MAC-Address! Just like "summary, lcd " and all other requests.
			

How to get the MAC-Address?

**Comment by YihaoPeng** [comment]
There is no MAC-Address in the response of bmminer API. But you can get it via HTTP request.
```
curl -uroot:root http://x.x.x.x/cgi-bin/get_system_info.cgi
```
https://github.com/btccom/libbtctools/blob/10798f9ca26c1b90aa5d7ee9b1506ecdfe5705c4/src/lua/scripts/minerScanner/antminer-http-cgi.lua#L240
